<?php
/*
 * SOZO Design Ltd
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    SOZO Design Ltd
 * @package     Sozo_Feedbucket
 * @copyright   Copyright (c) SOZO Design Ltd (https://sozodesign.co.uk)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

// @codingStandardsIgnoreFile
/* @var $block \Sozo\Feedbucket\Block\Frontend */
/* @var $escaper \Magento\Framework\Escaper */
?>
<!-- BEGIN FEEDBUCKET CODE {literal} -->
<script>
    window.feedbucketConfig = {
        <?= $block->getJsConfig()?>
    }
</script>
<script type="text/javascript">
    (function(k) {
        const s=document.createElement('script');s.module=true;s.defer=true;
        s.src="https://cdn.feedbucket.app/assets/feedbucket.js";
        s.dataset.feedbucket=k;document.head.appendChild(s);
    })('<?= $escaper->escapeUrl($block->getSecret()); ?>')
</script>
<!-- {/literal} END FEEDBUCKET CODE -->
